SET IDENTITY_INSERT tCus ON;

INSERT INTO tCus (CustomerID, EmailAddress,Password, FirstName, LastName, ShippingAddressID, BillingAddressID) VALUES
(1, 'allan.sherwood@yahoo.com','ABAqeBAABA', 'Allan', 'Sherwood', 1, 2),
(2, 'barryz@gmail.com','ABABqweAABA', 'Barry', 'Zimmer', 3, 3),
(3, 'christineb@solarone.com','ABAB12eAABA', 'Christine', 'Brown', 4, 4),
(4, 'david.goldstein@hotmail.com','ABAqweBAABA', 'David', 'Goldstein', 5, 6),
(5, 'erinv@gmail.com','ABABadsAABA', 'Erin', 'Valentino', 7, 7),
(6, 'frankwilson@sbcglobal.net','ABABAaasdABA', 'Frank Lee', 'Wilson', 8, 8),
(7, 'gary_hernandez@yahoo.com','ABAasdBAABA', 'Gary', 'Hernandez', 9, 10),
(8, 'heatheresway@mac.com','ABAadaBAABA', 'Heather', 'Esway', 11, 12),
(9, 'jbutt@gmail.com','ABABAadsABA', 'James', 'Butt', 13, 13),
(10, 'josephine_darakjy@darakjy.org','ABasdABAABA', 'Josephine', 'Darakjy', 14, 14),
(11, 'art@venere.org', 'ABABAadsABA','Art', 'Venere', 15, 16),
(12, 'lpaprocki@hotmail.com','ABABqwdqwdAABA', 'Lenna', 'Paprocki', 17, 17),
(13, 'donette.foller@cox.net','ABABasdAABA', 'Donette', 'Foller', 18, 18),
(14, 'simona@morasca.com','ABAadsBAABA', 'Simona', 'Morasca', 19, 19),
(15, 'mitsue_tollner@yahoo.com','ABABAadsABA', 'Mitsue', 'Tollner', 20, 21),
(16, 'leota@hotmail.com','ABABAadsABA', 'Leota', 'Dilliard', 22, 22),
(17, 'sage_wieser@cox.net','ABABadsAABA', 'Sage', 'Wieser', 23, 23),
(18, 'kris@gmail.com','ABAasdBAABA', 'Kris', 'Marrier', 24, 24),
(19, 'minna_amigon@yahoo.com','ABABAABA', 'Minna', 'Amigon', 25, 26),
(20, 'amaclead@gmail.com','ABAadsBAABA', 'Abel', 'Maclead', 27, 27),
(21, 'kiley.caldarera@aol.com','ABadABAABA','Kiley', 'Caldarera', 28, 28),
(22, 'gruta@cox.net','ABAqwdBAABA', 'Graciela', 'Ruta', 29, 29),
(23, 'calbares@gmail.com','ABABAABA', 'Cammy', 'Albares', 30, 30),
(24, 'mattie@aol.com','ABABAadsABA', 'Mattie', 'Poquette', 31, 31),
(25, 'meaghan@hotmail.com','ABasdABAABA', 'Meaghan', 'Garufi', 32, 32),
(26, 'gladys.rim@rim.org','ABABrsdfAABA', 'Gladys', 'Rim', 33, 33),
(27, 'yuki_whobrey@aol.com','ABABAABA', 'Yuki', 'Whobrey', 34, 34),
(28, 'fletcher.flosi@yahoo.com','ABadsABAABA', 'Fletcher', 'Flosi', 35, 35),
(29, 'bette_nicka@cox.net','ABABadAABA', 'Bette', 'Nicka', 36, 37),
(30, 'vinouye@aol.com', 'ABABAqeABA','Veronika', 'Inouye', 38, 38),
(31, 'willard@hotmail.com','ABAadsBAABA', 'Willard', 'Kolmetz', 39, 39),
(32, 'mroyster@royster.com','ABABasdAABA', 'Maryann', 'Royster', 40, 41),
(33, 'alisha@slusarski.com','ABABAAeBA', 'Alisha', 'Slusarski', 42, 43),
(34, 'allene_iturbide@cox.net','ABABaAABA', 'Allene', 'Iturbide', 44, 44),
(35, 'chanel.caudy@caudy.org', 'ABAccBAABA','Chanel', 'Caudy', 45, 45),
(36, 'ezekiel@chui.com', 'ABABAABA','Ezekiel', 'Chui', 46, 46),
(37, 'wkusko@yahoo.com', 'ABABAABA','Willow', 'Kusko', 47, 47),
(38, 'bfigeroa@aol.com','ABABAABA', 'Bernardo', 'Figeroa', 48, 48),
(39, 'ammie@corrio.com','ABABccAABA', 'Ammie', 'Corrio', 49, 49),
(40, 'francine_vocelka@vocelka.com','ABABAABA', 'Francine', 'Vocelka', 50, 51),
(41, 'ernie_stenseth@aol.com','ABABAABA', 'Ernie', 'Stenseth', 52, 52),
(42, 'albina@glick.com','ABABccAABA', 'Albina', 'Glick', 53, 53),
(43, 'asergi@gmail.com','ABABAABA', 'Alishia', 'Sergi', 54, 54),
(44, 'solange@shinko.com','ABABccABA', 'Solange', 'Shinko', 55, 55);

SET IDENTITY_INSERT tCus OFF;
